version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "14:00"
      timezone: "UTC"
    ignore:
      - dependency-name: "actions/setup-node"
        versions: [">=6.2.0"]
      - dependency-name: "actions/cache"
        versions: [">=5.0.2"]
