name: Build with PNPM

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Setup Node.js
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238  # v6
        with:
          node-version: "22"
          package-manager-cache: false

      - name: Install PNPM
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061  # v4.2.0

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@a7833574556fa59680c1b7cb190c1735db73ebf0  # v4.2.3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies for translation-and-context
        working-directory: ui/extensions/translation-and-context
        run: pnpm install

      - name: Build translation-and-context
        working-directory: ui/extensions/translation-and-context
        run: pnpm build

      - name: Run tests for translation-and-context
        working-directory: ui/extensions/translation-and-context
        run: pnpm test

      - name: Install dependencies for detection-context-explorer
        working-directory: ui/pages/detection-context-explorer
        run: pnpm install

      - name: Build detection-context-explorer
        working-directory: ui/pages/detection-context-explorer
        run: pnpm build

      - name: Run tests for detection-context-explorer
        working-directory: ui/pages/detection-context-explorer
        run: pnpm test
