name: Build with PNPM

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@20cf305ff2072d973412fa9b1e3a4f227bda3c76 # v2.14.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1

      - name: Setup Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f  # v6
        with:
          node-version: "22"
          package-manager-cache: false

      - name: Install PNPM
        uses: pnpm/action-setup@fe1e16a3373e0b04f1f1a959d0b7ca3b1fcef0a2  # v4

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb  # v5.0.1
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies for translation-and-context
        working-directory: ui/extensions/translation-and-context
        run: pnpm install

      - name: Build translation-and-context
        working-directory: ui/extensions/translation-and-context
        run: pnpm build

      - name: Run tests for translation-and-context
        working-directory: ui/extensions/translation-and-context
        run: pnpm test

      - name: Install dependencies for detection-context-explorer
        working-directory: ui/pages/detection-context-explorer
        run: pnpm install

      - name: Build detection-context-explorer
        working-directory: ui/pages/detection-context-explorer
        run: pnpm build

      - name: Run tests for detection-context-explorer
        working-directory: ui/pages/detection-context-explorer
        run: pnpm test
